import os

import numpy as np
import pandas as pd
from scipy.stats import shapiro, t

try:
    from statsmodels.stats.anova import AnovaRM
except ImportError as exc:
    raise ImportError(
        "statsmodels is required for repeated-measures ANOVA. Install with: pip install statsmodels"
    ) from exc


def resolve_transition_times_csv() -> str:
    """
    Find transition_times_results.csv generated by Main analysis.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    candidate_paths = [
        os.path.join(project_root, "transition_times_results.csv"),
        os.path.join(script_dir, "..", "transition_times_results.csv"),
        "transition_times_results.csv",
    ]

    csv_path = next((path for path in candidate_paths if os.path.exists(path)), None)
    if csv_path is None:
        searched = "\n - ".join(os.path.abspath(path) for path in candidate_paths)
        raise FileNotFoundError(
            "transition_times_results.csv not found.\n"
            f"Searched paths:\n - {searched}\n"
            "Run new_state_analysis/Main.py first to create it."
        )
    return csv_path


def analyze_scores(df: pd.DataFrame) -> pd.DataFrame:
    """
    Median-based descriptive statistics + Shapiro normality per numeric column.
    """
    df_numeric = df.select_dtypes(include=np.number)
    n = len(df_numeric)
    if n < 2:
        raise ValueError("Not enough rows for statistical analysis (need at least 2).")

    dfree = n - 1
    alpha = 0.05

    mean = df_numeric.mean()
    median = df_numeric.median()
    std = df_numeric.std()
    se = std / np.sqrt(n)
    t_critical = t.ppf(1 - alpha / 2, dfree)
    q1 = df_numeric.quantile(0.25)
    q3 = df_numeric.quantile(0.75)
    iqr = q3 - q1

    df_summary = pd.DataFrame(
        {
            "N": n,
            "Median": median,
            "Q1": q1,
            "Q3": q3,
            "IQR": iqr,
            "Mean": mean,
            "Std Dev": std,
            "Std Error": se,
            "CI Lower (95%)": mean - t_critical * se,
            "CI Upper (95%)": mean + t_critical * se,
        }
    )

    for col in df_numeric.columns:
        if df_numeric[col].dropna().shape[0] >= 3:
            _, p = shapiro(df_numeric[col].dropna())
            df_summary.loc[col, "Shapiro p"] = p
        else:
            df_summary.loc[col, "Shapiro p"] = np.nan

    return df_summary


def build_transition_time_wide_df(df_transitions: pd.DataFrame) -> pd.DataFrame:
    """
    Build participant-level wide table (B1-B8) from onset_to_onset transition times.
    Values are median transition times per participant and block.
    """
    required_cols = {"Participant_ID", "Test", "onset_to_onset"}
    missing = required_cols - set(df_transitions.columns)
    if missing:
        raise ValueError(f"Missing required columns in transition_times_results.csv: {sorted(missing)}")

    df = df_transitions.copy()
    df["Test"] = df["Test"].astype(str).str.upper().str.strip()
    df_blocks = df[df["Test"].str.match(r"^B[1-8]$")].copy()

    if df_blocks.empty:
        raise ValueError("No B1-B8 rows found in transition_times_results.csv")

    df_blocks["onset_to_onset"] = pd.to_numeric(df_blocks["onset_to_onset"], errors="coerce")
    df_blocks = df_blocks.dropna(subset=["onset_to_onset"])

    if df_blocks.empty:
        raise ValueError("No valid onset_to_onset values found for B1-B8")

    df_wide = (
        df_blocks.pivot_table(
            index="Participant_ID",
            columns="Test",
            values="onset_to_onset",
            aggfunc="median",
        )
        .reindex(columns=[f"B{i}" for i in range(1, 9)])
        .reset_index()
    )

    return df_wide


def run_log_rm_anova(df_wide: pd.DataFrame):
    """
    Run repeated-measures ANOVA across B1-B8 on log-transformed data.
    Uses log1p(x) to safely handle zero values.
    """
    block_cols = [f"B{i}" for i in range(1, 9)]
    df_blocks = df_wide[["Participant_ID", *block_cols]].copy()

    if (df_blocks[block_cols] < 0).any().any():
        raise ValueError("Negative transition times found; log-transform is not possible.")

    # ANOVA with repeated measures needs complete cases across all within-subject levels
    df_complete = df_blocks.dropna(subset=block_cols).copy()
    if df_complete.empty:
        raise ValueError("No complete B1-B8 cases available for repeated-measures ANOVA.")

    # Log-transform to reduce outlier influence
    df_complete[block_cols] = np.log1p(df_complete[block_cols])

    df_long = df_complete.melt(
        id_vars="Participant_ID",
        value_vars=block_cols,
        var_name="Block",
        value_name="log_onset_to_onset",
    )

    anova_model = AnovaRM(
        data=df_long,
        depvar="log_onset_to_onset",
        subject="Participant_ID",
        within=["Block"],
    )
    anova_result = anova_model.fit()

    anova_table = anova_result.anova_table.reset_index().rename(columns={"index": "Effect"})
    anova_table.insert(1, "N subjects", df_complete["Participant_ID"].nunique())

    return df_complete, df_long, anova_table


def main():
    csv_path = resolve_transition_times_csv()
    print(f"Using data file: {csv_path}")

    df_transitions = pd.read_csv(csv_path)
    df_wide = build_transition_time_wide_df(df_transitions)

    # Descriptive stats for transition time (onset_to_onset) in B1-B8
    summary_blocks = analyze_scores(df_wide.drop(columns=["Participant_ID"], errors="ignore"))

    # Repeated-measures ANOVA on log-transformed transition times
    df_log_wide, df_log_long, anova_log_results = run_log_rm_anova(df_wide)

    # Save outputs in project root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    wide_out = os.path.join(project_root, "block_transition_time_wide.csv")
    summary_out = os.path.join(project_root, "block_transition_time_summary.csv")
    log_wide_out = os.path.join(project_root, "block_transition_time_log_wide.csv")
    log_long_out = os.path.join(project_root, "block_transition_time_log_long.csv")
    anova_out = os.path.join(project_root, "block_transition_time_rm_anova_log_results.csv")

    df_wide.to_csv(wide_out, index=False)
    summary_blocks.to_csv(summary_out)
    df_log_wide.to_csv(log_wide_out, index=False)
    df_log_long.to_csv(log_long_out, index=False)
    anova_log_results.to_csv(anova_out, index=False)

    print("\n=== B1-B8 Median Transition Time (onset_to_onset) per Participant ===")
    print(df_wide.head())
    print("\n=== Descriptive Summary (Median/IQR): Transition Time (B1-B8) ===")
    print(summary_blocks)
    print("\n=== Repeated-Measures ANOVA on log1p(transition_time) ===")
    print(anova_log_results)

    print("\nSaved files:")
    print(f" - {wide_out}")
    print(f" - {summary_out}")
    print(f" - {log_wide_out}")
    print(f" - {log_long_out}")
    print(f" - {anova_out}")


if __name__ == "__main__":
    main()




